### ISSUE TITLE
Issues installing the project

### ISSUE THREAD

**Issue by kedano** [front/university-project#1]
Hi,

I get the following issue when I try to install the project:

`  [InvalidArgumentException]                                              
  Could not find package front/university-project with stability stable.  `

(I've used the following command ```$ composer create-project front/university-project university --no-interaction```)

I guess the project might miss a version-tag?

**Comment by roborn** [comment]
We do not have a version available to the public yet, so the instructions in the README file are not fully functional.

We will fix this soon.

**Comment by kedano** [comment]
Awesome. Do you have any timeframe? I guess I could just clone the projects and do the edits myself, but I guess there is further issues down the pipeline since it has not been tagged with a release version number yet.

**Comment by roborn** [comment]
We're refactoring some parts, to make it more inline with latest Drupal core additions, but we plan to release this before Dec 18th.

**Comment by thorandre** [comment]
I see that this was never closed. Refactoring is done and the installer should work now @kedano 

Great if you can do another test.
